
CREATE DATABASE IF NOT EXISTS Nex;

CONNECT Nex;

CREATE TABLE IF NOT EXISTS Scans (
	ScanID VARCHAR(10) NOT NULL,
	HWID VARCHAR(50) NOT NULL,
	Check01 VARCHAR(10) NOT NULL,
	Check02 VARCHAR(10) NOT NULL,
	Check03 VARCHAR(10) NOT NULL,
	Check04 VARCHAR(10) NOT NULL,
	Check05 VARCHAR(10) NOT NULL,
	Check06 VARCHAR(10) NOT NULL,
	deletedFiles VARCHAR(500) NOT NULL

) ENGINE = InnoDB default charset = utf8;